version: '3'
services:
    webserver:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./:/var/www/html/
            - type: bind
              source: ./apache2.conf
              target: /etc/apache2/apache2.conf
        ports:
            - "80:80"
    mariadb:
        image: mariadb:10.3.37
        restart: always
        environment:
            MARIADB_DATABASE: thabolao_naf_db
            MARIADB_USER: naf_tester
            MARIADB_PASSWORD: naf_tester_pw
            MARIADB_ROOT_PASSWORD: naf_tester_root_pw
        ports:
            - "3306:3306"
        volumes:
          - ./db-data:/var/lib/mysql