version: '3'
services:
    webserver:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./:/var/www/html/
            - type: bind
              source: ./apache2.conf
              target: /etc/apache2/apache2.conf
        ports:
            - "80:80"
    mariadb:
        image: mariadb:10.3.37
        restart: always
        environment:
            MARIADB_DATABASE: thabolao_naf_db
            MARIADB_USER: naf_tester
            MARIADB_PASSWORD: naf_tester_pw
            MARIADB_ROOT_PASSWORD: naf_tester_root_pw
        ports:
            - "3306:3306"
    flyway:
        image: flyway/flyway:9.14.1-alpine
        environment:
            FLYWAY_BASELINE_ON_MIGRATE: true
        volumes:
            - ./src/migrations/mariadb/10.3:/flyway/sql
        depends_on:
            - mariadb
        command: -url=jdbc:mariadb://mariadb:3306/thabolao_naf_db -user=naf_tester -password=naf_tester_pw -connectRetries=6 migrate

