version: '3'
services:
    webserver:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./:/var/www/html/
            - type: bind
              source: ./apache2.conf
              target: /etc/apache2/apache2.conf
        ports:
            - "80:80"
    mariadb:
        image: mariadb:10.3.37
        restart: always
        environment:
            MARIADB_DATABASE: "${DEV_DB_SCHEMA}"
            MARIADB_USER: "${DEV_DB_USERNAME}"
            MARIADB_PASSWORD: "${DEV_DB_PASSWORD}"
            MARIADB_ROOT_PASSWORD: naf_tester_root_pw
        ports:
            - "3306:3306"
    flyway:
        image: flyway/flyway:9.14.1-alpine
        environment:
            FLYWAY_BASELINE_ON_MIGRATE: true
        volumes:
            - ./src/migrations/mariadb/10.3:/flyway/sql
        depends_on:
            - mariadb
        command: > 
            -url=jdbc:mariadb://mariadb:3306/${DEV_DB_SCHEMA} -user=root 
            -password=naf_tester_root_pw -connectRetries=6 migrate